updating ES check update (tested also on previous versions of ES)

diff --git a/check_elasticsearch b/check_elasticsearch
--- a/check_elasticsearch
+++ b/check_elasticsearch
@@ -15,19 +15,25 @@
 #   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 
 PROGNAME=`basename $0`
-VERSION="Version 0.2.0,"
-AUTHOR="Andrew Lyon, Based on Mike Adolphs (http://www.matejunkie.com/) check_nginx.sh code"
-
+VERSION="Version 0.3.0,"
+AUTHOR="Andrew Lyon, Based on Mike Adolphs (http://www.matejunkie.com/) check_nginx.sh code. Authentication support added by Ryan Gallant"
 
 ST_OK=0
-ST_WR=0
+ST_WR=1
 ST_CR=2
 ST_UK=3
+epoch=`date +%s`
 hostname="localhost"
+user=elastic
+pass=changeme
+authentication=False
 port=9200
-status_page="/_cluster/health"
+status_page="_cluster/health"
 output_dir=/tmp
 secure=0
+carbon_key="system.:::name:::.cluster.app.elasticsearch.cluster"
+
+
 
 print_version() {
     echo "$VERSION $AUTHOR"
@@ -37,8 +43,8 @@ print_help() {
     print_version $PROGNAME $VERSION
     echo ""
     echo "$PROGNAME is a Nagios plugin to check the cluster status of elasticsearch."
-        echo "It also parses the status page to get a few useful variables out, and return"
-        echo "them in the output."
+    echo "It also parses the status page to get a few useful variables out, and return"
+    echo "them in the output."
     echo ""
     echo "$PROGNAME -H localhost -P 9200 -o /tmp"
     echo ""
@@ -50,9 +56,12 @@ print_help() {
     echo "  -o/--output-directory)"
     echo "     Specifies where to write the tmp-file that the check creates."
     echo "     Default is: /tmp"
-    echo "  -S/--status-page)"
-    echo "     Specifies the elasticsearch status page to check."
-    echo "     Default is: /_cluster/health"
+    echo "  -u/--username)"
+    echo "    Username for elasticsearch. Turns on authentication mode when set"
+    echo "  -p/--password)"
+    echo "    Password for elasticsearch. Turns on authentication mode when set"
+    echo "  -a/--auth)"
+    echo "    Turns on authentication mode with default credentials."
     exit $ST_UK
 }
 
@@ -74,43 +83,85 @@ while test -n "$1"; do
             port=$2
             shift
             ;;
-        --status-page|-S)
-            status_page=$2
+        --password|-p)
+            password=$2
+            authentication=True
+            shift
+            ;;
+        --username|-u)
+            username=$2
+            authentication=True
+            shift
+            ;;
+        --auth|-a)
+            authentication=True
             shift
             ;;
         --output-directory|-o)
             output_dir=$2
             shift
             ;;
-        *)
-            echo "Unknown argument: $1"
-            print_help
-            exit $ST_UK
+        --carbon-server|-c)
+            carbon_server=$2
+            shift
             ;;
+        --carbon-port|-C)
+            carbon_port=$2
+            shift
+            ;;
+        --carbon-key|-k)
+            carbon_key=$2
+            shift
+            ;;
+        *)
+        echo "Unknown argument: $1"
+        print_help
+        exit $ST_UK
+        ;;
     esac
     shift
 done
+
+if [ "$authentication" == True ]; then
+    pass="--password=${pass}"
+    user="--user=${user}"
+fi
 
 get_status() {
     filename=${PROGNAME}-${hostname}-${status_page}.1
     filename=`echo $filename | tr -d '\/'`
     filename=${output_dir}/${filename}
-        wget -q --header Host:stats -t 3 -T 3 http://${hostname}:${port}/${status_page}?pretty=true -O ${filename}
+    wget -q -t 3 -T 3 ${user} ${pass} http://${hostname}:${port}/${status_page}?pretty=true -O ${filename}
 }
 
 get_vals() {
-        #name=`grep cluster_name ${filename} | awk '{print $3}' | sed 's|[",]||g'`
-        name=`grep cluster_name ${filename} | awk 'BEGIN { FS = " : " } ; {print $2}' | sed 's|[",]||g'`
-        status=`grep status ${filename} | awk '{print $3}' | sed 's|[",]||g'`
-        timed_out=`grep timed_out ${filename} | awk '{print $3}' | sed 's|[",]||g'`
-        number_nodes=`grep number_of_nodes ${filename} | awk '{print $3}' | sed 's|[",]||g'`
-        number_data_nodes=`grep number_of_data_nodes ${filename} | awk '{print $3}' | sed 's|[",]||g'`
-        active_primary_shards=`grep active_primary_shards ${filename} | awk '{print $3}' | sed 's|[",]||g'`
-        active_shards=`grep active_shards ${filename} | awk '{print $3}' | sed 's|[",]||g'`
-        relocating_shards=`grep relocating_shards ${filename} | awk '{print $3}' | sed 's|[",]||g'`
-        initializing_shards=`grep initializing_shards ${filename} | awk '{print $3}' | sed 's|[",]||g'`
-        unassigned_shards=`grep unassigned_shards ${filename} | awk '{print $3}' | sed 's|[",]||g'`
-        rm -f ${filename}
+    name=$(grep '"cluster_name" :' ${filename} | awk -F '"' '{print $4}')
+    status=$(grep '"status" :' ${filename} | awk -F '"' '{print $4}')
+    timed_out=`grep timed_out ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+    number_nodes=`grep number_of_nodes ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+    number_data_nodes=`grep number_of_data_nodes ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+    active_primary_shards=`grep active_primary_shards ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+    active_shards=`grep active_shards ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+    relocating_shards=`grep relocating_shards ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+    initializing_shards=`grep initializing_shards ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+    delayed_unassigned_shards=`grep delayed_unassigned_shards ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+    unassigned_shards=`grep -w '"unassigned_shards' ${filename} | awk '{print $3}' | sed 's|[\r",]||g'`
+    rm -f ${filename}
+
+    # Determine the Nagios Status and Exit Code
+    if [ "$status" = "red" ]; then
+        NAGSTATUS="CRITICAL"
+        EXST=$ST_CR
+    elif [ "$status" = "yellow" ]; then
+        NAGSTATUS="WARNING"
+        EXST=$ST_WR
+    elif [ "$status" = "green" ]; then
+        NAGSTATUS="OK"
+        EXST=$ST_OK
+    else
+        NAGSTATUS="UNKNOWN"
+        EXST=$ST_UK
+    fi
 }
 
 do_output() {
@@ -123,45 +174,54 @@ active_primary_shards: $active_primary_shards; \
 active_shards: $active_shards; \
 relocating_shards: $relocating_shards; \
 initializing_shards: $initializing_shards; \
+delayed_unassigned_shards: $delayed_unassigned_shards; \
 unassigned_shards: $unassigned_shards "
 }
 
 do_perfdata() {
     #perfdata="'idle'=$iproc 'active'=$aproc 'total'=$tproc"
-    perfdata="'active_primary'=$active_primary_shards 'active'=$active_shards 'relocating'=$relocating_shards 'init'=$initializing_shards"
+    perfdata="'active_primary'=$active_primary_shards 'active'=$active_shards 'relocating'=$relocating_shards 'init'=$initializing_shards 'delay_unass'=$delayed_unassigned_shards 'unass'=$unassigned_shards"
+}
+
+do_graphite() {
+    if [ "$carbon_server" != "" -a "$carbon_port" != "" ]; then
+        key=$(echo $carbon_key | sed "s/:::name:::/$name/")
+        echo "$key.cluster.status                $EXST                  $epoch" | nc -w 2 $carbon_server $carbon_port
+        echo "$key.cluster.nodes.ttl             $number_nodes          $epoch" | nc -w 2 $carbon_server $carbon_port
+        echo "$key.cluster.nodes.data            $number_data_nodes     $epoch" | nc -w 2 $carbon_server $carbon_port
+        echo "$key.cluster.shards.active         $active_shards         $epoch" | nc -w 2 $carbon_server $carbon_port
+        echo "$key.cluster.shards.active_primary $active_primary_shards $epoch" | nc -w 2 $carbon_server $carbon_port
+        echo "$key.cluster.shards.initializing   $initializing_shards   $epoch" | nc -w 2 $carbon_server $carbon_port
+        echo "$key.cluster.shards.relocating     $relocating_shards     $epoch" | nc -w 2 $carbon_server $carbon_port
+        echo "$key.cluster.shards.delayed_unassigned     $delayed_unassigned_shards     $epoch" | nc -w 2 $carbon_server $carbon_port
+        echo "$key.cluster.shards.unassigned     $unassigned_shards     $epoch" | nc -w 2 $carbon_server $carbon_port
+        unset key
+    fi
 }
 
 # Here we go!
+which wget >/dev/null 2>&1
+if [ "$?" != "0" ]; then
+    echo "CRITICAL - wget is not installed"
+    exit $ST_CR
+fi
 get_status
 if [ ! -s "$filename" ]; then
-        echo "CRITICAL - Could not connect to server $hostname"
-        exit $ST_CR
+    echo "CRITICAL - Could not connect to server $hostname"
+    exit $ST_CR
 else
-        get_vals
-        if [ -z "$name" ]; then
-                echo "CRITICAL - Error parsing server output"
-                exit $ST_CR
-        else
-                do_output
-                do_perfdata
-        fi
+    get_vals
+    if [ -z "$name" ]; then
+        echo "CRITICAL - Error parsing server output"
+        exit $ST_CR
+    else
+        do_output
+        do_perfdata
+    do_graphite
+    fi
 fi
 
 COMPARE=$listql
 
-if [ "$status" = "red" ]; then
-        echo -n "CRITICAL"
-        EXST=$ST_CR
-elif [ "$status" = "yellow" ]; then
-        echo -n "WARNING"
-        EXST=$ST_WR
-elif [ "$status" = "green" ]; then
-        echo -n "OK"
-        EXST=$ST_OK
-else
-        echo -n "UNKNOWN"
-        EXST=$ST_UK
-fi
-
-echo " - ${output} | ${perfdata}"
+echo "${NAGSTATUS} - ${output} | ${perfdata}"
 exit $EXST
